#!/usr/bin/env node
/**
 * Build the project for static hosting (Netlify / GitHub Pages / any CDN).
 *
 * Why two passes?
 *   The TanStack Start prerender plugin imports `dist/server/server.js`,
 *   but the Cloudflare Vite plugin renames the server entry (it follows the
 *   `main` field in dist/server/wrangler.json — typically "index.js", and
 *   in some configurations a hashed filename). On a single `vite build`
 *   the prerender step therefore fails with ERR_MODULE_NOT_FOUND.
 *
 *   Pass 1: run `vite build` to produce dist/server/<actual-entry>.js.
 *   Then create a dist/server/server.js shim that re-exports the real entry.
 *   Pass 2: run `vite build` again with --emptyOutDir=false so the shim
 *   survives, and the prerender step now resolves successfully.
 *
 *   Finally, extract the prerendered client output into dist/ and strip the
 *   server bundle so the result is pure static HTML + assets.
 */
import { spawnSync } from "node:child_process";
import {
  existsSync,
  readdirSync,
  readFileSync,
  writeFileSync,
  rmSync,
  cpSync,
  mkdirSync,
  statSync,
} from "node:fs";
import { join, resolve } from "node:path";

const root = resolve(process.cwd());
const dist = join(root, "dist");
const distServer = join(dist, "server");

function findServerEntry() {
  if (!existsSync(distServer)) return null;

  // Preferred: read the actual entry from the emitted wrangler.json.
  const wranglerPath = join(distServer, "wrangler.json");
  if (existsSync(wranglerPath)) {
    try {
      const w = JSON.parse(readFileSync(wranglerPath, "utf8"));
      if (w.main && existsSync(join(distServer, w.main))) return w.main;
    } catch {
      /* fall through to filesystem scan */
    }
  }

  // Fallback: pick the first top-level .js file (excludes our own shim).
  const files = readdirSync(distServer).filter(
    (f) =>
      f.endsWith(".js") &&
      f !== "server.js" &&
      statSync(join(distServer, f)).isFile(),
  );
  return files[0] ?? null;
}

function writeServerShim() {
  const entry = findServerEntry();
  if (!entry) {
    console.error(
      "[build:static] Could not find a server entry file in dist/server/.",
    );
    return false;
  }
  const shim =
    `// Auto-generated by scripts/build-static.mjs.\n` +
    `// The TanStack prerender plugin imports './server.js'; the Cloudflare\n` +
    `// plugin emits the real entry under a different (sometimes hashed) name.\n` +
    `export * from "./${entry}";\n` +
    `export { default } from "./${entry}";\n`;
  writeFileSync(join(distServer, "server.js"), shim);
  console.log(`[build:static] Wrote dist/server/server.js -> ./${entry}`);
  return true;
}

function runVite(args) {
  const bin = join(root, "node_modules/vite/bin/vite.js");
  const result = spawnSync("node", [bin, ...args], { stdio: "inherit" });
  return result.status ?? 1;
}

console.log("[build:static] Pass 1/2: building server + client bundles...");
if (runVite(["build"]) !== 0) process.exit(1);

if (!writeServerShim()) process.exit(1);

console.log(
  "[build:static] Pass 2/2: re-running build to prerender pages (emptyOutDir disabled so the shim survives)...",
);
if (runVite(["build", "--emptyOutDir", "false"]) !== 0) process.exit(1);

// Pass 2 may overwrite the entry file; make sure the shim still exists.
if (!existsSync(join(distServer, "server.js"))) writeServerShim();

// Locate the prerendered client output.
const candidates = [
  ".output/public",
  ".tanstack/start/build/client",
  "dist/client",
].map((p) => join(root, p));
const source = candidates.find((p) => existsSync(p));
if (!source) {
  console.error(
    "[build:static] Could not find a prerendered output directory. Looked in:\n  " +
      candidates.map((c) => c.replace(root + "/", "")).join("\n  "),
  );
  process.exit(1);
}
console.log(`[build:static] Using static output from: ${source}`);

// Stage to a temp dir, then replace dist/ with just the static files.
// Staging avoids conflicts when `source` lives inside dist/ itself.
const tmp = join(root, ".dist-static-tmp");
if (existsSync(tmp)) rmSync(tmp, { recursive: true, force: true });
mkdirSync(tmp, { recursive: true });
cpSync(source, tmp, { recursive: true });

rmSync(dist, { recursive: true, force: true });
mkdirSync(dist, { recursive: true });
cpSync(tmp, dist, { recursive: true });
rmSync(tmp, { recursive: true, force: true });

// Defensive: strip any server-side artifacts that snuck in.
for (const name of ["server", "_server", "_worker.js"]) {
  const p = join(dist, name);
  if (existsSync(p)) {
    rmSync(p, { recursive: true, force: true });
    console.log(`[build:static] Removed ${name} from dist/`);
  }
}

const topLevel = readdirSync(dist).filter((f) =>
  statSync(join(dist, f)).isFile(),
);
const htmlFiles = topLevel.filter((f) => f.endsWith(".html"));
console.log(
  `[build:static] dist/ ready — ${htmlFiles.length} HTML file(s) at the root, ${topLevel.length} top-level files total.`,
);
