/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FoundersRouteImport } from './routes/founders'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClubMembersRouteImport } from './routes/club-members'
import { Route as IndexRouteImport } from './routes/index'

const FoundersRoute = FoundersRouteImport.update({
  id: '/founders',
  path: '/founders',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubMembersRoute = ClubMembersRouteImport.update({
  id: '/club-members',
  path: '/club-members',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/club-members': typeof ClubMembersRoute
  '/contact': typeof ContactRoute
  '/founders': typeof FoundersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/club-members': typeof ClubMembersRoute
  '/contact': typeof ContactRoute
  '/founders': typeof FoundersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/club-members': typeof ClubMembersRoute
  '/contact': typeof ContactRoute
  '/founders': typeof FoundersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/club-members' | '/contact' | '/founders'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/club-members' | '/contact' | '/founders'
  id: '__root__' | '/' | '/club-members' | '/contact' | '/founders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClubMembersRoute: typeof ClubMembersRoute
  ContactRoute: typeof ContactRoute
  FoundersRoute: typeof FoundersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/founders': {
      id: '/founders'
      path: '/founders'
      fullPath: '/founders'
      preLoaderRoute: typeof FoundersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club-members': {
      id: '/club-members'
      path: '/club-members'
      fullPath: '/club-members'
      preLoaderRoute: typeof ClubMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClubMembersRoute: ClubMembersRoute,
  ContactRoute: ContactRoute,
  FoundersRoute: FoundersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
